# Generated by Django 2.1.7 on 2019-04-01 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190328_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department'),
        ),
    ]
