# Generated by Django 2.1.7 on 2019-03-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190325_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_id',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='public', max_length=100),
        ),
    ]
