# Generated by Django 2.1.7 on 2019-04-01 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0002_auto_20190401_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
