# Generated by Django 2.1.7 on 2019-04-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_auto_20190401_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
